name: buzzer-com-timer

on:
  push:
    paths:
      - 'buzzer-com-timer/main.c'
jobs:
  buzzer-com-timer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: insper-embarcados/pico-build@v1
      - uses: insper-embarcados/actions-firmware-rubric-check@v0
        with:
          c_file: buzzer-com-timer/main.c
          rubric_file: buzzer-com-timer/rubric_firmware.yml
      - uses: insper-embarcados/actions-embedded-check@v1
        with:
          c_file: buzzer-com-timer/main.c
      - uses: insper-embarcados/actions-cppcheck@v1
        with:
          c_file: buzzer-com-timer/main.c
