name: jogo-reflexo

on:
  push:
    paths:
      - 'jogo-reflexo/main.c'
jobs:
  jogo-reflexo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: insper-embarcados/pico-build@v1
      - uses: insper-embarcados/actions-firmware-rubric-check@v0
        with:
          c_file: jogo-reflexo/main.c
          rubric_file: jogo-reflexo/rubric_firmware.yml
      - uses: insper-embarcados/actions-embedded-check@v1
        with:
          c_file: jogo-reflexo/main.c
      - uses: insper-embarcados/actions-cppcheck@v1
        with:
          c_file: jogo-reflexo/main.c
