name: teclado-matricial

on:
  push:
    paths:
      - 'teclado-matricial/main.c'
jobs:
  teclado-matricial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: insper-embarcados/pico-build@v1
      - uses: insper-embarcados/actions-firmware-rubric-check@v0
        with:
          c_file: teclado-matricial/main.c
          rubric_file: teclado-matricial/rubric_firmware.yml
      - uses: insper-embarcados/actions-embedded-check@v1
        with:
          c_file: teclado-matricial/main.c
      - uses: insper-embarcados/actions-cppcheck@v1
        with:
          c_file: teclado-matricial/main.c
